const weatherCodeDescription = {
  '0': 'Unknown',
  '10000': 'Clear, Sunny',
  '11000': 'Mostly Clear',
  '11010': 'Partly Cloudy',
  '11020': 'Mostly Cloudy',
  '10010': 'Cloudy',
  '11030': 'Partly Cloudy and Mostly Clear',
  '21000': 'Light Fog',
  '21010': 'Mostly Clear and Light Fog',
  '21020': 'Partly Cloudy and Light Fog',
  '21030': 'Mostly Cloudy and Light Fog',
  '21060': 'Mostly Clear and Fog',
  '21070': 'Partly Cloudy and Fog',
  '21080': 'Mostly Cloudy and Fog',
  '20000': 'Fog',
  '42040': 'Partly Cloudy and Drizzle',
  '42030': 'Mostly Clear and Drizzle',
  '42050': 'Mostly Cloudy and Drizzle',
  '40000': 'Drizzle',
  '42000': 'Light Rain',
  '42130': 'Mostly Clear and Light Rain',
  '42140': 'Partly Cloudy and Light Rain',
  '42150': 'Mostly Cloudy and Light Rain',
  '42090': 'Mostly Clear and Rain',
  '42080': 'Partly Cloudy and Rain',
  '42100': 'Mostly Cloudy and Rain',
  '40010': 'Rain',
  '42110': 'Mostly Clear and Heavy Rain',
  '42020': 'Partly Cloudy and Heavy Rain',
  '42120': 'Mostly Cloudy and Heavy Rain',
  '42010': 'Heavy Rain',
  '51150': 'Mostly Clear and Flurries',
  '51160': 'Partly Cloudy and Flurries',
  '51170': 'Mostly Cloudy and Flurries',
  '50010': 'Flurries',
  '51000': 'Light Snow',
  '51020': 'Mostly Clear and Light Snow',
  '51030': 'Partly Cloudy and Light Snow',
  '51040': 'Mostly Cloudy and Light Snow',
  '51220': 'Drizzle and Light Snow',
  '51050': 'Mostly Clear and Snow',
  '51060': 'Partly Cloudy and Snow',
  '51070': 'Mostly Cloudy and Snow',
  '50000': 'Snow',
  '51010': 'Heavy Snow',
  '51190': 'Mostly Clear and Heavy Snow',
  '51200': 'Partly Cloudy and Heavy Snow',
  '51210': 'Mostly Cloudy and Heavy Snow',
  '51100': 'Drizzle and Snow',
  '51080': 'Rain and Snow',
  '51140': 'Snow and Freezing Rain',
  '51120': 'Snow and Ice Pellets',
  '60000': 'Freezing Drizzle',
  '60030': 'Mostly Clear and Freezing drizzle',
  '60020': 'Partly Cloudy and Freezing drizzle',
  '60040': 'Mostly Cloudy and Freezing drizzle',
  '62040': 'Drizzle and Freezing Drizzle',
  '62060': 'Light Rain and Freezing Drizzle',
  '62050': 'Mostly Clear and Light Freezing Rain',
  '62030': 'Partly Cloudy and Light Freezing Rain',
  '62090': 'Mostly Cloudy and Light Freezing Rain',
  '62000': 'Light Freezing Rain',
  '62130': 'Mostly Clear and Freezing Rain',
  '62140': 'Partly Cloudy and Freezing Rain',
  '62150': 'Mostly Cloudy and Freezing Rain',
  '60010': 'Freezing Rain',
  '62120': 'Drizzle and Freezing Rain',
  '62200': 'Light Rain and Freezing Rain',
  '62220': 'Rain and Freezing Rain',
  '62070': 'Mostly Clear and Heavy Freezing Rain',
  '62020': 'Partly Cloudy and Heavy Freezing Rain',
  '62080': 'Mostly Cloudy and Heavy Freezing Rain',
  '62010': 'Heavy Freezing Rain',
  '71100': 'Mostly Clear and Light Ice Pellets',
  '71110': 'Partly Cloudy and Light Ice Pellets',
  '71120': 'Mostly Cloudy and Light Ice Pellets',
  '71020': 'Light Ice Pellets',
  '71080': 'Mostly Clear and Ice Pellets',
  '71070': 'Partly Cloudy and Ice Pellets',
  '71090': 'Mostly Cloudy and Ice Pellets',
  '70000': 'Ice Pellets',
  '71050': 'Drizzle and Ice Pellets',
  '71060': 'Freezing Rain and Ice Pellets',
  '71150': 'Light Rain and Ice Pellets',
  '71170': 'Rain and Ice Pellets',
  '71030': 'Freezing Rain and Heavy Ice Pellets',
  '71130': 'Mostly Clear and Heavy Ice Pellets',
  '71140': 'Partly Cloudy and Heavy Ice Pellets',
  '71160': 'Mostly Cloudy and Heavy Ice Pellets',
  '71010': 'Heavy Ice Pellets',
  '80010': 'Mostly Clear and Thunderstorm',
  '80030': 'Partly Cloudy and Thunderstorm',
  '80020': 'Mostly Cloudy and Thunderstorm',
  '80000': 'Thunderstorm',
};

export const weatherCodeDayMap = new Map<string, string>(
  Object.entries(weatherCodeDescription)
);

const isoCountries: { [key: string]: string } = {
  AF: 'Afghanistan',
  AX: 'Aland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua And Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia And Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  CV: 'Cape Verde',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo',
  CD: 'Congo, Democratic Republic',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  CI: "Cote D'Ivoire",
  HR: 'Croatia',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (Malvinas)',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island & Mcdonald Islands',
  VA: 'Holy See (Vatican City State)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran, Islamic Republic Of',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle Of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KR: 'Korea',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: "Lao People's Democratic Republic",
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libyan Arab Jamahiriya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia, Federated States Of',
  MD: 'Moldova',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  AN: 'Netherlands Antilles',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestinian Territory, Occupied',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  BL: 'Saint Barthelemy',
  SH: 'Saint Helena',
  KN: 'Saint Kitts And Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin',
  PM: 'Saint Pierre And Miquelon',
  VC: 'Saint Vincent And Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome And Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia And Sandwich Isl.',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard And Jan Mayen',
  SZ: 'Swaziland',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad And Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks And Caicos Islands',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States',
  UM: 'United States Outlying Islands',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Viet Nam',
  VG: 'Virgin Islands, British',
  VI: 'Virgin Islands, U.S.',
  WF: 'Wallis And Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export const isoCountriesMap = new Map<string, string>(
  Object.entries(isoCountries)
);
