const OPENWEATHER_API_KEY = process.env.REACT_APP_OPEN_WEATHER_KEY;
const STORMGLASS_API_KEY = process.env.REACT_APP_STORMGLASS_KEY;
const TOMORROWIO_API_KEY = process.env.REACT_APP_TOMORROWIO_KEY;
const GOOGLE_CALENDAR_API_KEY = process.env.REACT_APP_GOOGLE_KEY;
const GOOGLE_CALENDAR_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;

export {
  OPENWEATHER_API_KEY,
  STORMGLASS_API_KEY,
  TOMORROWIO_API_KEY,
  GOOGLE_CALENDAR_API_KEY,
  GOOGLE_CALENDAR_CLIENT_ID,
};
