const OPENWEATHER_API_KEY = process.env.REACT_APP_OPEN_WEATHER_KEY;
const STORMGLASS_API_KEY = process.env.REACT_APP_STORMGLASS_KEY;
const TOMORROWIO_API_KEY = process.env.REACT_APP_TOMORROWIO_KEY;

export { OPENWEATHER_API_KEY, STORMGLASS_API_KEY, TOMORROWIO_API_KEY };
